---
nginx_package_name: nginx
nginx_service_name: nginx
nginx_become: true
nginx_docroot: "{{ nginx_docroot_map.get(ansible_os_family, '/usr/share/nginx/html') }}"
nginx_index_path: "{{ nginx_docroot }}/index.html"
nginx_site_config_path: "{{ nginx_site_config_path_map.get(ansible_os_family, '/etc/nginx/conf.d/default.conf') }}"
nginx_default_site_path: "{{ nginx_default_site_path_map.get(ansible_os_family, '') }}"
nginx_site_listen_port: 80
nginx_server_name: localhost
nginx_page_title: "Welcome from Ansible"
nginx_page_message: "Nginx was installed and configured by the nginx role."
nginx_manage_service: true
